### ISSUE TITLE
Error due to write permissions as module not permitted to write templates

### ISSUE THREAD

**Issue by mdhishaamakhtar** [YashKumarVerma/javascript-templates-package#7]
Cannot generate smoketrees template in Node.js when installed globally using npm. This is the error that it throws.
![c2498d99-bc32-4619-b5fe-c4b86e8b0310](https://user-images.githubusercontent.com/58990970/82781274-fa3f3f80-9e76-11ea-9d5a-30fa0df39245.jpeg)

**Comment by YashKumarVerma** [comment]
Hey there! I'm working to solve the issue. 
Here's the progress.

- [x] I was able to reproduce the error.
- [x] Detected Source of Error: permissions
- [x] Working with `sudo` ![image](https://user-images.githubusercontent.com/14032427/82823378-123db000-9ec5-11ea-8534-88ffc2a29b77.png)
- [x] Error reason traces
- [x] Fix found
- [x] Testing fixes

**Comment by YashKumarVerma** [comment]
@mdhishaamakhtar 
I've recently pushed and released version 2.0.2 patch to fix this issue. Hope it works fine.

**Comment by mdhishaamakhtar** [comment]
It is resolved.
